#! /bin/sh

# launch polybar
$HOME/.config/polybar/launch.sh &

# launch brillo normal
xrandr --output VGA-1 --brightness 0.80

# background
feh --bg-scale /home/fercho/Wallpapers/01.png

# keyboard leds on
xset led on

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d "" "" "" "" ""

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
